# Generated by Django 4.2.4 on 2023-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='behaviors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=50)),
                ('field3', models.CharField(max_length=50)),
                ('field4', models.CharField(max_length=1000)),
                ('field5', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=50)),
                ('field3', models.CharField(max_length=50)),
                ('field4', models.CharField(max_length=100)),
                ('field5', models.CharField(max_length=1000)),
                ('field6', models.CharField(max_length=100)),
                ('field7', models.CharField(max_length=1000)),
                ('field8', models.CharField(max_length=1000)),
            ],
        ),
    ]
